export interface PricingItem {
  SNo: number
  Item: string
  Price: number
}

export type PricingData = Record<string, PricingItem[]>

export const pricingData: PricingData = {
  "Men's Clothing": [
    { SNo: 1, Item: "Shirt", Price: 100 },
    { SNo: 2, Item: "Shirt Silk", Price: 130 },
    { SNo: 3, Item: "Shirt Woolen", Price: 130 },
    { SNo: 4, Item: "T Shirt", Price: 90 },
    { SNo: 5, Item: "Pant", Price: 110 },
    { SNo: 6, Item: "Jeans", Price: 125 },
    { SNo: 7, Item: "Coat", Price: 300 },
    { SNo: 8, Item: "Waist Coat", Price: 140 },
    { SNo: 9, Item: "Long Coat", Price: 410 },
    { SNo: 10, Item: "Jacket Full Sleeves", Price: 300 },
    { SNo: 11, Item: "Jacket Half Sleeves", Price: 230 },
    { SNo: 12, Item: "Jacket with Hood", Price: 375 },
    { SNo: 13, Item: "Leather Jacket", Price: 430 },
    { SNo: 14, Item: "Sweater", Price: 160 },
    { SNo: 15, Item: "Long Pullover", Price: 130 },
    { SNo: 16, Item: "Kurta", Price: 125 },
    { SNo: 17, Item: "Kurta Heavy", Price: 170 },
    { SNo: 18, Item: "Dhoti", Price: 120 },
    { SNo: 19, Item: "Safari Suit Coat", Price: 210 },
    { SNo: 20, Item: "Safari Suit Pant", Price: 125 },
    { SNo: 21, Item: "Achkan", Price: 400 },
    { SNo: 22, Item: "Shorts", Price: 90 },
    { SNo: 23, Item: "Pyjama", Price: 90 },
    { SNo: 24, Item: "Capri", Price: 90 },
    { SNo: 25, Item: "Sweat Pants", Price: 120 },
    { SNo: 26, Item: "Track Pant", Price: 120 },
    { SNo: 27, Item: "Swimming Costume", Price: 45 },
    { SNo: 28, Item: "Under Wear", Price: 45 },
    { SNo: 29, Item: "Vest", Price: 45 },
  ],
  "Women's Clothing": [
    { SNo: 30, Item: "Kurta Plain", Price: 125 },
    { SNo: 31, Item: "Kurta Very Heavy", Price: 270 },
    { SNo: 32, Item: "Plazo Plain", Price: 90 },
    { SNo: 33, Item: "Plazo Heavy", Price: 150 },
    { SNo: 34, Item: "Dupatta", Price: 75 },
    { SNo: 35, Item: "Dupatta Heavy", Price: 100 },
    { SNo: 36, Item: "Saree Plain", Price: 160 },
    { SNo: 37, Item: "Saree Heavy", Price: 250 },
    { SNo: 38, Item: "Saree Very Heavy", Price: 325 },
    { SNo: 39, Item: "Petticoat", Price: 65 },
    { SNo: 40, Item: "Blouse", Price: 65 },
    { SNo: 41, Item: "Blouse Heavy", Price: 95 },
    { SNo: 42, Item: "Dress Plain", Price: 280 },
    { SNo: 43, Item: "Dress Very Heavy", Price: 440 },
    { SNo: 44, Item: "Dress Long Plain", Price: 380 },
    { SNo: 45, Item: "Dress Long Very Heavy", Price: 580 },
    { SNo: 46, Item: "Lehnga Plain", Price: 430 },
    { SNo: 47, Item: "Lehnga Heavy", Price: 555 },
    { SNo: 48, Item: "Lehnga Very Heavy", Price: 700 },
    { SNo: 49, Item: "Skirt Short Plain", Price: 190 },
    { SNo: 50, Item: "Skirt Short Heavy", Price: 280 },
    { SNo: 51, Item: "Skirt Long Plain", Price: 265 },
    { SNo: 52, Item: "Skirt Long Heavy", Price: 300 },
    { SNo: 53, Item: "Top Plain", Price: 125 },
    { SNo: 54, Item: "Top Heavy", Price: 185 },
    { SNo: 55, Item: "Top Woollen", Price: 180 },
    { SNo: 56, Item: "Shirt", Price: 100 },
    { SNo: 57, Item: "T Shirt", Price: 90 },
    { SNo: 58, Item: "Pants", Price: 110 },
    { SNo: 59, Item: "Jeans", Price: 125 },
    { SNo: 60, Item: "Jumper", Price: 180 },
    { SNo: 61, Item: "Dangree", Price: 180 },
    { SNo: 62, Item: "Legging", Price: 90 },
    { SNo: 63, Item: "Capri", Price: 90 },
    { SNo: 64, Item: "Slacks", Price: 98 },
    { SNo: 65, Item: "Stole Plain", Price: 75 },
    { SNo: 66, Item: "Stole Heavy", Price: 100 },
    { SNo: 67, Item: "Shawl Plain", Price: 130 },
    { SNo: 68, Item: "Shawl Heavy", Price: 170 },
    { SNo: 69, Item: "Scarf", Price: 60 },
    { SNo: 70, Item: "Coat", Price: 300 },
    { SNo: 71, Item: "Long Coat", Price: 440 },
    { SNo: 72, Item: "Jacket Full Sleeves", Price: 300 },
    { SNo: 73, Item: "Jacket Half Sleeves", Price: 220 },
    { SNo: 74, Item: "Jacket with Hood", Price: 370 },
    { SNo: 75, Item: "Sweat Shirt with Hood", Price: 190 },
    { SNo: 76, Item: "Sweater Full Sleeves Plain", Price: 130 },
    { SNo: 77, Item: "Sweater Full Sleeves Heavy", Price: 160 },
    { SNo: 78, Item: "Sweater Half Sleeves Plain", Price: 90 },
    { SNo: 79, Item: "Sweater Half Sleeves Heavy", Price: 125 },
    { SNo: 80, Item: "Long Pullover", Price: 190 },
    { SNo: 81, Item: "Stocking", Price: 90 },
    { SNo: 82, Item: "Track Pant", Price: 120 },
  ],
  "Kids' Clothing": [
    { SNo: 83, Item: "Shirt", Price: 80 },
    { SNo: 84, Item: "Shirt Woolen", Price: 100 },
    { SNo: 85, Item: "T Shirt", Price: 70 },
    { SNo: 86, Item: "Top Plain", Price: 90 },
    { SNo: 87, Item: "Top Heavy", Price: 140 },
    { SNo: 88, Item: "Pants", Price: 90 },
    { SNo: 89, Item: "Jeans", Price: 90 },
    { SNo: 90, Item: "Capri", Price: 70 },
    { SNo: 91, Item: "Shorts", Price: 70 },
    { SNo: 92, Item: "Jumper", Price: 140 },
    { SNo: 93, Item: "Dangree", Price: 140 },
    { SNo: 94, Item: "Frock Plain", Price: 170 },
    { SNo: 95, Item: "Frock Heavy", Price: 220 },
    { SNo: 96, Item: "Frock Very Heavy", Price: 270 },
    { SNo: 97, Item: "Skirt Plain", Price: 240 },
    { SNo: 98, Item: "Baby Blanket", Price: 270 },
    { SNo: 99, Item: "Skirt Heavy", Price: 290 },
    { SNo: 100, Item: "Skirt Very Heavy", Price: 380 },
    { SNo: 101, Item: "Dress Plain", Price: 220 },
    { SNo: 102, Item: "Dress Very Heavy", Price: 360 },
    { SNo: 103, Item: "Sherwani", Price: 350 },
    { SNo: 104, Item: "Kurta Plain", Price: 90 },
    { SNo: 105, Item: "Kurta Very Heavy", Price: 215 },
    { SNo: 106, Item: "Salwar Plain", Price: 70 },
    { SNo: 107, Item: "Salwar Heavy", Price: 120 },
    { SNo: 108, Item: "Dupatta", Price: 50 },
    { SNo: 109, Item: "Dupatta Very Heavy", Price: 130 },
    { SNo: 110, Item: "Blouse", Price: 50 },
    { SNo: 111, Item: "Blouse Heavy", Price: 70 },
    { SNo: 112, Item: "Lehnga Plain", Price: 350 },
    { SNo: 113, Item: "Lehnga Heavy", Price: 460 },
    { SNo: 114, Item: "Coat", Price: 235 },
    { SNo: 115, Item: "Waist Coat", Price: 100 },
    { SNo: 116, Item: "Long Coat", Price: 380 },
    { SNo: 117, Item: "Long Pullover", Price: 150 },
    { SNo: 118, Item: "Jacket Full Sleeves", Price: 230 },
    { SNo: 119, Item: "Jacket Half Sleeves", Price: 180 },
    { SNo: 120, Item: "Jacket with Hood", Price: 290 },
    { SNo: 121, Item: "Sweater Full Sleeves Plain", Price: 100 },
    { SNo: 122, Item: "Sweater Full Sleeves Heavy", Price: 130 },
    { SNo: 123, Item: "Sweater Half Sleeves Plain", Price: 70 },
    { SNo: 124, Item: "Sweater Half Sleeves Heavy", Price: 90 },
    { SNo: 125, Item: "Sweat Shirt", Price: 130 },
    { SNo: 126, Item: "Sweat Shirt with Hood", Price: 150 },
    { SNo: 127, Item: "Swimming Costume", Price: 30 },
    { SNo: 128, Item: "Legging", Price: 70 },
    { SNo: 129, Item: "Track Pant", Price: 90 },
    { SNo: 130, Item: "Baby Blanket", Price: 270 },
  ],
  "Other Items": [
    { SNo: 131, Item: "Soft Toy Small", Price: 220 },
    { SNo: 132, Item: "Soft Toy Medium", Price: 360 },
    { SNo: 133, Item: "Soft Toy Large", Price: 490 },
    { SNo: 134, Item: "Soft Toy Extra Large", Price: 600 },
    { SNo: 135, Item: "Soft Toy Full Size", Price: 800 },
    { SNo: 136, Item: "Suit Case Small", Price: 270 },
    { SNo: 137, Item: "Suit Case Medium", Price: 410 },
    { SNo: 138, Item: "Suit Case Large", Price: 560 },
    { SNo: 139, Item: "Suit Case Extra Large", Price: 700 },
    { SNo: 140, Item: "Handbag Canvass Jute Cloth based Large", Price: 400 },
    { SNo: 141, Item: "Handbag Canvass Jute Cloth based Small", Price: 300 },
    { SNo: 142, Item: "Handbag Leather Small", Price: 430 },
    { SNo: 143, Item: "Handbag Leather Large", Price: 630 },
    { SNo: 144, Item: "Handkerchief", Price: 40 },
    { SNo: 145, Item: "Hat", Price: 170 },
    { SNo: 146, Item: "Cap", Price: 170 },
    { SNo: 147, Item: "Muffler", Price: 100 },
    { SNo: 148, Item: "Rain Coat", Price: 220 },
    { SNo: 149, Item: "Tie", Price: 40 },
    { SNo: 150, Item: "Bath Robe", Price: 160 },
    { SNo: 151, Item: "Belt", Price: 220 },
    { SNo: 152, Item: "Wallet", Price: 220 },
    { SNo: 153, Item: "Car Seat Cover", Price: 190 },
    { SNo: 154, Item: "Gloves", Price: 60 },
    { SNo: 155, Item: "Socks", Price: 60 },
    { SNo: 156, Item: "Face Mask", Price: 50 },
    { SNo: 157, Item: "Seat Cover", Price: 50 },
  ],
  "Household Items": [
    { SNo: 158, Item: "Curtain Door", Price: 170 },
    { SNo: 159, Item: "Curtain Door With Lining", Price: 280 },
    { SNo: 160, Item: "Curtain Window", Price: 130 },
    { SNo: 161, Item: "Curtain Window With Lining", Price: 230 },
    { SNo: 162, Item: "Curtain Belt", Price: 50 },
    { SNo: 163, Item: "Blind Door", Price: 280 },
    { SNo: 164, Item: "Blind Window", Price: 220 },
    { SNo: 165, Item: "Blanket Single", Price: 335 },
    { SNo: 166, Item: "Blanket Single 2 Ply", Price: 420 },
    { SNo: 167, Item: "Blanket Double", Price: 435 },
    { SNo: 168, Item: "Blanket Double 2 Ply", Price: 535 },
    { SNo: 169, Item: "Quilt Single", Price: 420 },
    { SNo: 170, Item: "Quilt Double", Price: 535 },
    { SNo: 171, Item: "Quilt Cover Single", Price: 240 },
    { SNo: 172, Item: "Quilt Cover Double", Price: 290 },
    { SNo: 173, Item: "Duvet", Price: 80 },
    { SNo: 174, Item: "Duvet Double", Price: 125 },
    { SNo: 175, Item: "Bed Sheet Single", Price: 135 },
    { SNo: 176, Item: "Bed Sheet Double", Price: 165 },
    { SNo: 177, Item: "Bed Spread Single", Price: 240 },
    { SNo: 178, Item: "Bed Spread Double", Price: 290 },
    { SNo: 179, Item: "Sofa Cover Small", Price: 50 },
    { SNo: 180, Item: "Sofa Cover Medium", Price: 100 },
    { SNo: 181, Item: "Sofa Cover Large", Price: 150 },
    { SNo: 182, Item: "Cushion Covers", Price: 50 },
    { SNo: 183, Item: "Cushion Covers Medium", Price: 100 },
    { SNo: 184, Item: "Cushion Covers Large", Price: 150 },
    { SNo: 185, Item: "Cushion Small", Price: 130 },
    { SNo: 186, Item: "Cushion Medium", Price: 190 },
    { SNo: 187, Item: "Cushion Large", Price: 250 },
    { SNo: 188, Item: "Pillow Covers", Price: 50 },
    { SNo: 189, Item: "Chair Covers", Price: 50 },
    { SNo: 190, Item: "Hand Towel", Price: 40 },
    { SNo: 191, Item: "Towel Large", Price: 130 },
    { SNo: 192, Item: "Carpet", Price: 40 },
    { SNo: 193, Item: "Table Cloth Small", Price: 70 },
    { SNo: 194, Item: "Table Cloth Large", Price: 130 },
    { SNo: 195, Item: "Table Mat", Price: 50 },
    { SNo: 196, Item: "Foot Mats", Price: 60 },
    { SNo: 197, Item: "Mattress Double", Price: 2000 },
    { SNo: 198, Item: "Bed Head", Price: 1500 },
    { SNo: 199, Item: "Mattress Single", Price: 1000 },
  ],
  "Shoes": [
    { SNo: 200, Item: "Sport Shoes (Pair)", Price: 310 },
    { SNo: 201, Item: "Canvass Shoes (Pair)", Price: 310 },
    { SNo: 202, Item: "Leather Shoes (Pair)", Price: 520 },
    { SNo: 203, Item: "Suede Leather Shoes", Price: 610 },
    { SNo: 204, Item: "Ankle Length Boots", Price: 740 },
    { SNo: 205, Item: "Mid Length Boots", Price: 1000 },
    { SNo: 206, Item: "Knee Length Boots", Price: 1400 },
    { SNo: 207, Item: "Sandals (Pair)", Price: 300 },
    { SNo: 208, Item: "Slippers (Pair)", Price: 230 },
    { SNo: 209, Item: "Helmet", Price: 300 },
  ],
}
